version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive

formatters:
  enable:
    - gofumpt

issues:
  exclude-use-default: false

output:
  format: colored-line-number
